apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: eval
     name: fastapi-pvc
  hostPath:
    path: "/home/ubuntu/eval/fastapi/app"
  storageClassName: local-path